import Head from "next/head";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect, useMemo } from "react";
import simulator from "./simulator";
import MechState, { MechStatus, MechType } from "../src/types/MechState";
import AtomState, { AtomStatus, AtomType } from "../src/types/AtomState";
import AtomFaucetState from "../src/types/AtomFaucetState";
import BoardConfig from "../src/types/BoardConfig";
import Frame from "../src/types/Frame";
import Unit from "./unit";
import UnitState, { BgStatus, BorderStatus, UnitText } from "../src/types/UnitState";
import Operator, { OPERATOR_TYPES } from "../src/types/Operator";
import Delivery from "./delivery";
import Summary from "./summary";
import Tutorial from "./tutorial";
import { isGridOOB, areGridsNeighbors } from "../src/helpers/gridHelpers";
import OperatorGridBg from "../src/components/OperatorGridBg";
import { DIM, PROGRAM_SIZE_MAX, DEMO_SOLUTIONS, N_CYCLES } from "../src/constants/constants";
import { useTranslation } from "react-i18next";
import "../config/i18n";
import LanguageSelector from "../src/components/LanguageSelector";
import ConnectWalletStardisc from "../src/components/ConnectWalletStardisc";
import { useAccount, useStarknetExecute } from "@starknet-react/core";
import packSolution, { programsToInstructionSets } from "../src/helpers/packSolution";
import { SIMULATOR_ADDR } from "../src/components/SimulatorContract";
import Solution from "../src/types/Solution";
import Leaderboard from "../src/components/Leaderboard";
import {
    Accordion,
    AccordionDetails,
    AccordionSummary,
    Box,
    createTheme,
    Paper,
    styled,
    SxProps,
    ThemeProvider,
    Tooltip,
} from "@mui/material";
import {
    saveSolutionToLocal,
    getSolutionFromLocal,
    getNamespaceFromLocal,
    removeSolutionFromLocal,
} from "../src/helpers/localStorage";
import SavedSolutionElement from "../src/components/savedSolutionElement";
import SocialMedia from "../src/components/SocialMedia";
import MechProgramming from "../src/components/MechProgramming";
import Grid from "@mui/system/Unstable_Grid";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import theme from "../styles/theme";

const gridStyles: SxProps = {
    display: "flex",
    flexDirection: "row",
    border: 1,
    borderColor: "secondary.light",
};

export default function Home() {
    const { t } = useTranslation();

    const Panel = ({ children }) => {
        return (
            <Box
                sx={{
                    textAlign: "center",
                    flex: 1,
                }}
            >
                {children}
            </Box>
        );
    };

    return (
        <>
            <Head>
                <title>MuMu</title>
                <meta name="MuMu" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ThemeProvider theme={theme}>
                <Box sx={{ height: "100vh" }} display="flex" flexDirection="column">
                    <Grid container spacing={1} flex={1.25} disableEqualOverflow>
                        <Grid xs={3} sx={gridStyles}>
                            <Panel>
                                <div className={styles.title}>
                                    <h2>{t("MuMu")}</h2>
                                    <p>{t("Subtitle")}</p>
                                    <SocialMedia />
                                </div>
                                <ConnectWalletStardisc />

                                <LanguageSelector />

                                <Tutorial />
                            </Panel>
                        </Grid>
                        <Grid xs={6} sx={gridStyles}>
                            <Panel>Board</Panel>
                        </Grid>
                        <Grid xs={3} sx={gridStyles}>
                            <Panel>Stats</Panel>
                        </Grid>
                    </Grid>
                    <Box flex={1} flexShrink={0} overflow="scroll">
                        <Panel>
                            <Accordion>
                                <AccordionSummary
                                    expandIcon={<ExpandMoreIcon />}
                                    aria-controls="panel1a-content"
                                    id="panel1a-header"
                                >
                                    Operators
                                </AccordionSummary>
                                <AccordionDetails>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus
                                    ex, sit amet blandit leo lobortis eget.
                                </AccordionDetails>
                            </Accordion>
                            <Accordion>
                                <AccordionSummary
                                    expandIcon={<ExpandMoreIcon />}
                                    aria-controls="panel1a-content"
                                    id="panel1a-header"
                                >
                                    Mechs
                                </AccordionSummary>
                                <AccordionDetails>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse malesuada lacus
                                    ex, sit amet blandit leo lobortis eget.
                                </AccordionDetails>
                            </Accordion>
                        </Panel>
                    </Box>
                </Box>
            </ThemeProvider>
        </>
    );
}
